/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Heroes;

import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Daniel
 */
public class HeroesPrincipal extends javax.swing.JFrame {
ArrayList <Personajes> personajitos= new ArrayList();
    /**
     * Creates new form HeroesPrincipal
     */
    public HeroesPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarHeroes = new javax.swing.JFrame();
        AgregarHeroes_ = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_debilidad = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_poder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_hp = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_fuerza = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_agilidad = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_agilidadM = new javax.swing.JFormattedTextField();
        bt_add = new javax.swing.JButton();
        combo_universo = new javax.swing.JComboBox<>();
        Listar = new javax.swing.JFrame();
        ListaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree_heroes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListillaPersonajes = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        ListarPop = new javax.swing.JMenuItem();
        eliminarPop = new javax.swing.JMenuItem();
        jp_Principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_Simular = new javax.swing.JButton();
        bt_Agregar1 = new javax.swing.JButton();
        bt_Listar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        AgregarHeroes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarHeroes_.setBackground(new java.awt.Color(132, 216, 216));
        AgregarHeroes_.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("HP (Puntos de Vida)");
        AgregarHeroes_.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 180, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Nombre");
        AgregarHeroes_.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));
        AgregarHeroes_.add(tf_debilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 30));
        AgregarHeroes_.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Super Poder");
        AgregarHeroes_.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 40));

        tf_poder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_poderActionPerformed(evt);
            }
        });
        AgregarHeroes_.add(tf_poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Debilidad");
        AgregarHeroes_.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 40));

        tf_hp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hpActionPerformed(evt);
            }
        });
        AgregarHeroes_.add(tf_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Fuerza");
        AgregarHeroes_.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 40));

        tf_fuerza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_fuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fuerzaActionPerformed(evt);
            }
        });
        AgregarHeroes_.add(tf_fuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Agilidad");
        AgregarHeroes_.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, 40));

        tf_agilidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_agilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_agilidadActionPerformed(evt);
            }
        });
        AgregarHeroes_.add(tf_agilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Agilidad Mental");
        AgregarHeroes_.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 160, 40));

        tf_agilidadM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tf_agilidadM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_agilidadMActionPerformed(evt);
            }
        });
        AgregarHeroes_.add(tf_agilidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, 30));

        bt_add.setBackground(new java.awt.Color(0, 0, 153));
        bt_add.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        bt_add.setForeground(new java.awt.Color(153, 204, 255));
        bt_add.setText("Agregar");
        bt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addMouseClicked(evt);
            }
        });
        AgregarHeroes_.add(bt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 180, 100));

        combo_universo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marvel", "DC", "Capcom", "MK" }));
        combo_universo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_universoActionPerformed(evt);
            }
        });
        AgregarHeroes_.add(combo_universo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 180, 50));

        AgregarHeroes.getContentPane().add(AgregarHeroes_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        Listar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPanel.setBackground(new java.awt.Color(102, 0, 153));

        jtree_heroes.setBackground(new java.awt.Color(51, 0, 51));
        jtree_heroes.setForeground(new java.awt.Color(204, 204, 204));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Heroes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capcom");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Midway");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        jtree_heroes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jtree_heroes);

        ListillaPersonajes.setBackground(new java.awt.Color(51, 0, 51));
        ListillaPersonajes.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(ListillaPersonajes);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Listar");

        javax.swing.GroupLayout ListaPanelLayout = new javax.swing.GroupLayout(ListaPanel);
        ListaPanel.setLayout(ListaPanelLayout);
        ListaPanelLayout.setHorizontalGroup(
            ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(216, 216, 216))
        );
        ListaPanelLayout.setVerticalGroup(
            ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        Listar.getContentPane().add(ListaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        ListarPop.setText("Listar");
        ListarPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPopActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ListarPop);

        eliminarPop.setText("jMenuItem2");
        jPopupMenu1.add(eliminarPop);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_Principal.setBackground(new java.awt.Color(102, 0, 0));
        jp_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marvel- vs -Dc- vs -Capcom- vs -MK");
        jp_Principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        bt_Simular.setBackground(new java.awt.Color(255, 51, 51));
        bt_Simular.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        bt_Simular.setForeground(new java.awt.Color(102, 0, 0));
        bt_Simular.setText("Simulacion");
        bt_Simular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_SimularMouseClicked(evt);
            }
        });
        jp_Principal.add(bt_Simular, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 230, 60));

        bt_Agregar1.setBackground(new java.awt.Color(255, 51, 51));
        bt_Agregar1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        bt_Agregar1.setForeground(new java.awt.Color(102, 0, 0));
        bt_Agregar1.setText("Agregar Personaje");
        bt_Agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Agregar1MouseClicked(evt);
            }
        });
        jp_Principal.add(bt_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 230, 60));

        bt_Listar1.setBackground(new java.awt.Color(255, 51, 51));
        bt_Listar1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        bt_Listar1.setForeground(new java.awt.Color(102, 0, 0));
        bt_Listar1.setText("Listar Personajes");
        bt_Listar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Listar1MouseClicked(evt);
            }
        });
        jp_Principal.add(bt_Listar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 230, 60));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jp_Principal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 700, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Downloads\\heroe (1).png")); // NOI18N
        jp_Principal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        getContentPane().add(jp_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hpActionPerformed

    private void tf_fuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fuerzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fuerzaActionPerformed

    private void tf_agilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_agilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_agilidadActionPerformed

    private void tf_agilidadMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_agilidadMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_agilidadMActionPerformed

    private void combo_universoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_universoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_universoActionPerformed

    private void bt_SimularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_SimularMouseClicked
        //Ir a la pantalla de simular
        
    }//GEN-LAST:event_bt_SimularMouseClicked

    private void bt_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseClicked
        String nombreP=tf_nombre.getText();
        String poderP=tf_poder.getText();
        String debilidadP=tf_debilidad.getText();
        int fuerzaP= Integer.parseInt(tf_fuerza.getText());
        int agilidadP= Integer.parseInt(tf_agilidad.getText());
        int agilidadMP= Integer.parseInt(tf_agilidadM.getText());
        int hpP= Integer.parseInt(tf_hp.getText());
        String universoP=(String)combo_universo.getSelectedItem();
        
        Personajes heroes= new Personajes(nombreP,poderP,debilidadP,fuerzaP,agilidadP,agilidadMP,hpP,universoP);
        personajitos.add(heroes);
        
        DefaultTreeModel M= (DefaultTreeModel) jtree_heroes.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) M.getRoot();
        
        if(universoP == "Marvel"){
            //Le puse universe por steven universe jajajaj
            DefaultMutableTreeNode universe = (DefaultMutableTreeNode) raiz.getChildAt(0);
            DefaultMutableTreeNode nPersonajes= new DefaultMutableTreeNode (heroes);
            universe.add(nPersonajes);
            jtree_heroes.
        }
        
        tf_nombre.setText("");
        tf_poder.setText("");
        tf_debilidad.setText("");
        tf_fuerza.setText("");
        tf_agilidad.setText("");
        tf_agilidadM.setText("");
        tf_hp.setText("");
        
    }//GEN-LAST:event_bt_addMouseClicked

    private void tf_poderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_poderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_poderActionPerformed

    private void bt_Agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Agregar1MouseClicked
        //Agregar cosas
        AgregarHeroes.setVisible(true);
        AgregarHeroes.pack();
    }//GEN-LAST:event_bt_Agregar1MouseClicked

    private void bt_Listar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Listar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_Listar1MouseClicked

    private void ListarPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPopActionPerformed
        // TODO add your handling code here:
        //Action
    }//GEN-LAST:event_ListarPopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeroesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeroesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeroesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeroesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeroesPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AgregarHeroes;
    private javax.swing.JPanel AgregarHeroes_;
    private javax.swing.JPanel ListaPanel;
    private javax.swing.JFrame Listar;
    private javax.swing.JMenuItem ListarPop;
    private javax.swing.JList<String> ListillaPersonajes;
    private javax.swing.JButton bt_Agregar1;
    private javax.swing.JButton bt_Listar1;
    private javax.swing.JButton bt_Simular;
    private javax.swing.JButton bt_add;
    private javax.swing.JComboBox<String> combo_universo;
    private javax.swing.JMenuItem eliminarPop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp_Principal;
    private javax.swing.JTree jtree_heroes;
    private javax.swing.JFormattedTextField tf_agilidad;
    private javax.swing.JFormattedTextField tf_agilidadM;
    private javax.swing.JTextField tf_debilidad;
    private javax.swing.JFormattedTextField tf_fuerza;
    private javax.swing.JFormattedTextField tf_hp;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_poder;
    // End of variables declaration//GEN-END:variables
}
